### PR TITLE
Add a lineage file to begin getting upstream updates

### PR DESCRIPTION
**Pull request by dav3r**
#  #

## 🗣 Description ##

This PR adds a `lineage.yml` file to this repository making it a descendant of [`cisagov/skeleton-tf-module`](https://github.com/cisagov/skeleton-tf-module).

## 💭 Motivation and context ##

This will enable this repo to receive upstream updates and remain current with our latest development practices.

## 🧪 Testing ##

Visual inspection.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

### CODE REVIEW

**Comment by mcdonnnj** [comment]
Should we just carve the time to resolve https://github.com/cisagov/cool-dns-dmarc-import/pull/3 instead? This PR would have the same full resolution issues that PR's completion is held up by with regard to old Terraform support.

**Comment by jsf9k** [comment]
> Should we just carve the time to resolve #3 instead? This PR would have the same full resolution issues that PR's completion is held up by with regard to old Terraform support.

I like this better.  This repo is one that got left behind when we moved to TF 1.0.  I didn't know what moving to TF 1.0 entailed, so I couldn't move forward with #3.  #3 and #2 both live in an "Ancient PRs" tab in my browser.

**Comment by dav3r** [comment]
> > Should we just carve the time to resolve #3 instead? This PR would have the same full resolution issues that PR's completion is held up by with regard to old Terraform support.
> 
> I like this better. This repo is one that got left behind when we moved to TF 1.0. I didn't know what moving to TF 1.0 entailed, so I couldn't move forward with #3. #3 and #2 both live in an "Ancient PRs" tab in my browser.

Yes, I am fully in favor of closing this PR and wrapping up #3 - I had completely forgotten that it existed.  @mcdonnnj do you have time to take on finishing #3 or would you prefer to hand it over to me?

**Comment by mcdonnnj** [comment]
> > > Should we just carve the time to resolve #3 instead? This PR would have the same full resolution issues that PR's completion is held up by with regard to old Terraform support.
> > 
> > 
> > I like this better. This repo is one that got left behind when we moved to TF 1.0. I didn't know what moving to TF 1.0 entailed, so I couldn't move forward with #3. #3 and #2 both live in an "Ancient PRs" tab in my browser.
> 
> Yes, I am fully in favor of closing this PR and wrapping up #3 - I had completely forgotten that it existed. @mcdonnnj do you have time to take on finishing #3 or would you prefer to hand it over to me?

@dav3r I can start work on it this week or you can take over. I'm fine with either option.

**Comment by dav3r** [comment]
> > @mcdonnnj do you have time to take on finishing #3 or would you prefer to hand it over to me?
> 
> @dav3r I can start work on it this week or you can take over. I'm fine with either option.

I'm going to work on the re-skeletonizing PR for `cisagov/cool-dns-dmarc-import` first.  If I get that done before you're able to start working on #3, then I can take it over.

**Comment by dav3r** [comment]
Closing this PR in favor of finishing #3.

**Comment by mcdonnnj** [comment]
> 

@dav3r Just for clarity: are you going to start working on re-skeletonizing _this_ project (`cisagov/cool-dns-dmarc-import`) as you said or [cisagov/cool-dns-57.69.64.in-addr.arpa](https://github.com/cisagov/cool-dns-57.69.64.in-addr.arpa)?

**Comment by dav3r** [comment]
> > 
> 
> @dav3r Just for clarity: are you going to start working on re-skeletonizing _this_ project (`cisagov/cool-dns-dmarc-import`) as you said or [cisagov/cool-dns-57.69.64.in-addr.arpa](https://github.com/cisagov/cool-dns-57.69.64.in-addr.arpa)?

Doh- I pasted in the wrong repo name in my previous comment.  As you probably inferred, I am indeed working on reskeletonizing **[`cisagov/cool-dns-57.69.64.in-addr.arpa`](https://github.com/cisagov/cool-dns-57.69.64.in-addr.arpa)** first.  Let's ping one another before either of us picks up work on #3 so that we don't accidentally both work on it.

**Comment by jsf9k** [comment]
If #3 gets merged, then I can merge #2, and then _all_ my ancient PRs will be put to rest!

**Pull request closed without merging**
